# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(530, 140, 320, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.create3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.create3.setObjectName("create3")
        self.gridLayout.addWidget(self.create3, 6, 2, 1, 1)
        self.create4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.create4.setObjectName("create4")
        self.gridLayout.addWidget(self.create4, 7, 2, 1, 1)
        self.event_occur2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.event_occur2.setObjectName("event_occur2")
        self.gridLayout.addWidget(self.event_occur2, 5, 4, 1, 1)
        self.create2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.create2.setObjectName("create2")
        self.gridLayout.addWidget(self.create2, 5, 2, 1, 1)
        self.event_occur4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.event_occur4.setObjectName("event_occur4")
        self.gridLayout.addWidget(self.event_occur4, 7, 4, 1, 1)
        self.event_occur3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.event_occur3.setObjectName("event_occur3")
        self.gridLayout.addWidget(self.event_occur3, 6, 4, 1, 1)
        self.event_wait4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.event_wait4.setObjectName("event_wait4")
        self.gridLayout.addWidget(self.event_wait4, 7, 3, 1, 1)
        self.create1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.create1.setObjectName("create1")
        self.gridLayout.addWidget(self.create1, 4, 2, 1, 1)
        self.event_occur1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.event_occur1.setObjectName("event_occur1")
        self.gridLayout.addWidget(self.event_occur1, 4, 4, 1, 1)
        self.create5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.create5.setObjectName("create5")
        self.gridLayout.addWidget(self.create5, 8, 2, 1, 1)
        self.event_wait1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.event_wait1.setObjectName("event_wait1")
        self.gridLayout.addWidget(self.event_wait1, 4, 3, 1, 1)
        self.event_wait3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.event_wait3.setObjectName("event_wait3")
        self.gridLayout.addWidget(self.event_wait3, 6, 3, 1, 1)
        self.event_occur5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.event_occur5.setObjectName("event_occur5")
        self.gridLayout.addWidget(self.event_occur5, 8, 4, 1, 1)
        self.event_wait5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.event_wait5.setObjectName("event_wait5")
        self.gridLayout.addWidget(self.event_wait5, 8, 3, 1, 1)
        self.event_wait2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.event_wait2.setObjectName("event_wait2")
        self.gridLayout.addWidget(self.event_wait2, 5, 3, 1, 1)
        self.release1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.release1.setObjectName("release1")
        self.gridLayout.addWidget(self.release1, 4, 5, 1, 1)
        self.release2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.release2.setObjectName("release2")
        self.gridLayout.addWidget(self.release2, 5, 5, 1, 1)
        self.release3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.release3.setObjectName("release3")
        self.gridLayout.addWidget(self.release3, 6, 5, 1, 1)
        self.release4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.release4.setObjectName("release4")
        self.gridLayout.addWidget(self.release4, 7, 5, 1, 1)
        self.release5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.release5.setObjectName("release5")
        self.gridLayout.addWidget(self.release5, 8, 5, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(50, 140, 341, 301))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.memsize1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.memsize1.setObjectName("memsize1")
        self.gridLayout_2.addWidget(self.memsize1, 0, 2, 1, 1)
        self.pid2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.pid2.setObjectName("pid2")
        self.gridLayout_2.addWidget(self.pid2, 1, 0, 1, 1)
        self.pid1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.pid1.setObjectName("pid1")
        self.gridLayout_2.addWidget(self.pid1, 0, 0, 1, 1)
        self.prl5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.prl5.setObjectName("prl5")
        self.gridLayout_2.addWidget(self.prl5, 4, 1, 1, 1)
        self.memsize3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.memsize3.setObjectName("memsize3")
        self.gridLayout_2.addWidget(self.memsize3, 2, 2, 1, 1)
        self.memsize5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.memsize5.setObjectName("memsize5")
        self.gridLayout_2.addWidget(self.memsize5, 4, 2, 1, 1)
        self.pid3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.pid3.setObjectName("pid3")
        self.gridLayout_2.addWidget(self.pid3, 2, 0, 1, 1)
        self.prl3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.prl3.setObjectName("prl3")
        self.gridLayout_2.addWidget(self.prl3, 2, 1, 1, 1)
        self.pid4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.pid4.setObjectName("pid4")
        self.gridLayout_2.addWidget(self.pid4, 3, 0, 1, 1)
        self.pid5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.pid5.setObjectName("pid5")
        self.gridLayout_2.addWidget(self.pid5, 4, 0, 1, 1)
        self.prl2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.prl2.setObjectName("prl2")
        self.gridLayout_2.addWidget(self.prl2, 1, 1, 1, 1)
        self.prl1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.prl1.setObjectName("prl1")
        self.gridLayout_2.addWidget(self.prl1, 0, 1, 1, 1)
        self.prl4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.prl4.setObjectName("prl4")
        self.gridLayout_2.addWidget(self.prl4, 3, 1, 1, 1)
        self.memsize4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.memsize4.setObjectName("memsize4")
        self.gridLayout_2.addWidget(self.memsize4, 3, 2, 1, 1)
        self.memsize2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.memsize2.setObjectName("memsize2")
        self.gridLayout_2.addWidget(self.memsize2, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(339, 30, 230, 31))
        self.label_11.setObjectName("label_11")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(91, 101, 22, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 101, 42, 18))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 101, 70, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(396, 101, 130, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(660, 101, 56, 18))
        self.label_5.setObjectName("label_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(400, 140, 121, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.status1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.status1.setObjectName("status1")
        self.verticalLayout.addWidget(self.status1)
        self.status2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.status2.setObjectName("status2")
        self.verticalLayout.addWidget(self.status2)
        self.status3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.status3.setObjectName("status3")
        self.verticalLayout.addWidget(self.status3)
        self.status4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.status4.setObjectName("status4")
        self.verticalLayout.addWidget(self.status4)
        self.status5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.status5.setObjectName("status5")
        self.verticalLayout.addWidget(self.status5)
        self.progressdisplay = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.progressdisplay.setGeometry(QtCore.QRect(50, 460, 801, 201))
        self.progressdisplay.setObjectName("progressdisplay")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(780, 30, 75, 23))
        self.closeButton.setObjectName("closeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "进程状态转换"))
        self.create3.setText(_translate("MainWindow", "create"))
        self.create4.setText(_translate("MainWindow", "create"))
        self.event_occur2.setText(_translate("MainWindow", "event occur"))
        self.create2.setText(_translate("MainWindow", "create"))
        self.event_occur4.setText(_translate("MainWindow", "event occur"))
        self.event_occur3.setText(_translate("MainWindow", "event occur"))
        self.event_wait4.setText(_translate("MainWindow", "event wait"))
        self.create1.setText(_translate("MainWindow", "create"))
        self.event_occur1.setText(_translate("MainWindow", "event occur"))
        self.create5.setText(_translate("MainWindow", "create"))
        self.event_wait1.setText(_translate("MainWindow", "event wait"))
        self.event_wait3.setText(_translate("MainWindow", "event wait"))
        self.event_occur5.setText(_translate("MainWindow", "event occur"))
        self.event_wait5.setText(_translate("MainWindow", "event wait"))
        self.event_wait2.setText(_translate("MainWindow", "event wait"))
        self.release1.setText(_translate("MainWindow", "release"))
        self.release2.setText(_translate("MainWindow", "release"))
        self.release3.setText(_translate("MainWindow", "release"))
        self.release4.setText(_translate("MainWindow", "release"))
        self.release5.setText(_translate("MainWindow", "release"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">进程状态转换模拟</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">PID</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">优先级</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">占用内存</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">当前状态</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">可选指令</span></p></body></html>"))
        self.status1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.status2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.status3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.status4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.status5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.closeButton.setText(_translate("MainWindow", "关闭"))

